### ISSUE TITLE
System.Management.WmiNetUtilsHelper' threw an exception.

### ISSUE THREAD

**Issue by yangjieshao** [Jinjinov/Hardware.Info#49]
### Library version
11.1.0.0
### OS & OS version
Windows 11  22H2
### Describe the bug
```
The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
System.TypeInitializationException
System.Management
Boolean IsNoContextMTA()
   at System.Management.MTAHelper.IsNoContextMTA()
   at System.Management.MTAHelper.CreateInMTA(Type)
   at System.Management.ManagementPath.CreateWbemPath(String)
   at System.Management.ManagementPath..ctor(String path)
   at System.Management.ManagementScope..ctor(String path)
   at System.Management.ManagementObjectSearcher..ctor(String, String, EnumerationOptions)
   at Hardware.Info.Windows.HardwareInfoRetrieval.GetOs()
   at Hardware.Info.Windows.HardwareInfoRetrieval..ctor(Nullable`1 enumerationOptionsTimeout)
   at Hardware.Info.HardwareInfo..ctor(Boolean useAsteriskInWMI, Nullable`1 timeoutInWMI)
```

Publish setting:
```
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net7.0\publish\win-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net7.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>
</Project>
```

if  PublishTrimmed is true  threw exception.
if  PublishTrimmed is false ,  Program is ok

**Comment by Jinjinov** [comment]
Thank you for noticing this, I will look into it!

**Comment by Jinjinov** [comment]
This is a known problem: https://github.com/dotnet/core/issues/7051#issuecomment-1071484354

Unfortunately the only solution I found suggests setting `PublishTrimmed` to `false`:
https://stackoverflow.com/questions/66919258/system-typeinitializationexception-the-type-initializer-for-system-management

I will look into it some more.

**Comment by Jinjinov** [comment]
Unfortunately I couldn't find a solution.
