### ISSUE TITLE
System.Management.ManagementException Monitor List on RDP

### ISSUE THREAD

**Issue by Agent-JY** [Jinjinov/Hardware.Info#74]
### Win 11 (64 bit)

**Hardware.Info.HardwareInfo.RefreshMonitorList() throws an exeption when there is no monitor connected and the computer is controlled via RDP.**

Code:
```
public class HardwareInformation
{
    private static readonly HardwareInfo HardwareInfo = new();

    public void GetInfo()
    {
        HardwareInfo.RefreshAll();
    }
}
```

Exception message:
```
System.Management.ManagementException: Not supported
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Hardware.Info.Windows.HardwareInfoRetrieval.GetMonitorList()
   at Hardware.Info.HardwareInfo.RefreshMonitorList()
   at Hardware.Info.HardwareInfo.RefreshAll()
```

**Comment by Jinjinov** [comment]
Thank you for reporting this!

I will take a look when I have time.

**Comment by Jinjinov** [comment]
Fixed in https://github.com/Jinjinov/Hardware.Info/releases/tag/v101.0.0.1
